### ISSUE TITLE
git push problem (eslint)

### ISSUE THREAD

**Issue by belozer** [rebem/css#3]
```
$ git push                 

> rebem-css@0.2.0 prepush /home/sergey/projects/rebem-css
> npm start prepush


> rebem-css@0.2.0 start /home/sergey/projects/rebem-css
> start-runner start-rebem-preset "prepush"

→ env: start
→ env: NODE_ENV = test
→ env: done

→ files: start
→ files: lib/index.js
→ files: test/lib/index.js
→ files: done

→ eslint: start
Error: Cannot find module 'estraverse-fb'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at monkeypatch (/home/sergey/projects/rebem-css/node_modules/babel-eslint/index.js:59:32)
    at Object.exports.parse (/home/sergey/projects/rebem-css/node_modules/babel-eslint/index.js:385:5)
    at parse (/home/sergey/projects/rebem-css/node_modules/eslint/lib/eslint.js:628:27)
    at EventEmitter.module.exports.api.verify (/home/sergey/projects/rebem-css/node_modules/eslint/lib/eslint.js:768:19)
    at processText (/home/sergey/projects/rebem-css/node_modules/eslint/lib/cli-engine.js:263:31)
    at processFile (/home/sergey/projects/rebem-css/node_modules/eslint/lib/cli-engine.js:298:18)
    at executeOnFile (/home/sergey/projects/rebem-css/node_modules/eslint/lib/cli-engine.js:682:23)
```

**Comment by belozer** [comment]
After install module 'estraverse-fb'

```
~/projects/rebem-css on ⭠ master ⌚ 20:16:53
$ git push                 

> rebem-css@0.2.0 prepush /home/sergey/projects/rebem-css
> npm start prepush


> rebem-css@0.2.0 start /home/sergey/projects/rebem-css
> start-runner start-rebem-preset "prepush"

→ env: start
→ env: NODE_ENV = test
→ env: done

→ files: start
→ files: lib/index.js
→ files: test/lib/index.js
→ files: done

→ eslint: start

/home/sergey/projects/rebem-css/lib/index.js
  1:1  error  Rule 'no-empty-label' was removed and replaced by: no-labels                                      no-empty-label
  1:1  error  Rule 'space-after-keywords' was removed and replaced by: keyword-spacing                          space-after-keywords
  1:1  error  Rule 'space-return-throw-case' was removed and replaced by: keyword-spacing                       space-return-throw-case
  1:1  error  Rule 'no-arrow-condition' was removed and replaced by: no-confusing-arrow, no-constant-condition  no-arrow-condition

/home/sergey/projects/rebem-css/test/lib/index.js
  1:1  error  Rule 'no-empty-label' was removed and replaced by: no-labels                                      no-empty-label
  1:1  error  Rule 'space-after-keywords' was removed and replaced by: keyword-spacing                          space-after-keywords
  1:1  error  Rule 'space-return-throw-case' was removed and replaced by: keyword-spacing                       space-return-throw-case
  1:1  error  Rule 'no-arrow-condition' was removed and replaced by: no-confusing-arrow, no-constant-condition  no-arrow-condition

```

**Comment by belozer** [comment]
I updated `eslint-config-rebem": "0.3.x"` to `eslint-config-rebem": "1.1.x"`. Now all works.

**Comment by deepsweet** [comment]
I have updated dev deps, everything should be ok now. thanks!
